import { StyleSheet } from "react-native";

export const AUTH_COLORS = {
  background: "#070a14",
  surface: "rgba(9, 14, 27, 0.78)",
  surfaceStrong: "rgba(13, 20, 37, 0.9)",
  surfaceSoft: "rgba(15, 23, 42, 0.72)",
  border: "rgba(148, 163, 184, 0.18)",
  borderStrong: "rgba(96, 165, 250, 0.28)",
  text: "#e5eefc",
  textMuted: "#94a3b8",
  textSoft: "#cbd5e1",
  primary: "#3b82f6",
  primaryStrong: "#2563eb",
  primaryTint: "rgba(59, 130, 246, 0.16)",
  success: "#22c55e",
  danger: "#f87171",
  fieldBackground: "rgba(2, 6, 23, 0.58)",
  fieldBorder: "rgba(148, 163, 184, 0.2)",
  fieldPlaceholder: "rgba(148, 163, 184, 0.76)",
};

export const AUTH_PLACEHOLDER_COLOR = AUTH_COLORS.fieldPlaceholder;

export const authStyles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "transparent",
  },
  keyboardAvoid: {
    flex: 1,
  },
  container: {
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 32,
    gap: 14,
  },
  heroCard: {
    borderRadius: 24,
    paddingHorizontal: 18,
    paddingVertical: 20,
    backgroundColor: AUTH_COLORS.surface,
    borderWidth: 1,
    borderColor: AUTH_COLORS.borderStrong,
    gap: 10,
    shadowColor: "#000000",
    shadowOpacity: 0.24,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
  },
  heroBadge: {
    alignSelf: "flex-start",
    minHeight: 28,
    borderRadius: 999,
    paddingHorizontal: 10,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: AUTH_COLORS.primaryTint,
    borderWidth: 1,
    borderColor: AUTH_COLORS.borderStrong,
  },
  heroBadgeText: {
    color: AUTH_COLORS.textSoft,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.8,
    textTransform: "uppercase",
  },
  heroHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 14,
  },
  logoCircle: {
    width: 56,
    height: 56,
    borderRadius: 28,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(59,130,246,0.16)",
    borderWidth: 1,
    borderColor: AUTH_COLORS.borderStrong,
  },
  heroCopy: {
    flex: 1,
    gap: 4,
  },
  title: {
    fontSize: 28,
    lineHeight: 34,
    fontWeight: "800",
    color: AUTH_COLORS.text,
  },
  subtitle: {
    fontSize: 14,
    lineHeight: 20,
    color: AUTH_COLORS.textMuted,
  },
  heroPillRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  heroPill: {
    minHeight: 30,
    borderRadius: 999,
    paddingHorizontal: 10,
    backgroundColor: AUTH_COLORS.surfaceSoft,
    borderWidth: 1,
    borderColor: AUTH_COLORS.border,
    alignItems: "center",
    justifyContent: "center",
  },
  heroPillText: {
    color: AUTH_COLORS.textSoft,
    fontSize: 12,
    fontWeight: "600",
  },
  langRow: {
    flexDirection: "row",
    gap: 8,
  },
  langBtn: {
    minHeight: 34,
    borderRadius: 999,
    paddingHorizontal: 14,
    borderWidth: 1,
    borderColor: AUTH_COLORS.border,
    backgroundColor: AUTH_COLORS.surfaceSoft,
    alignItems: "center",
    justifyContent: "center",
  },
  langBtnActive: {
    borderColor: AUTH_COLORS.borderStrong,
    backgroundColor: AUTH_COLORS.primary,
  },
  langBtnText: {
    color: AUTH_COLORS.textSoft,
    fontSize: 12,
    fontWeight: "700",
  },
  langBtnTextActive: {
    color: "#ffffff",
  },
  card: {
    borderRadius: 22,
    paddingHorizontal: 16,
    paddingVertical: 16,
    backgroundColor: AUTH_COLORS.surface,
    borderWidth: 1,
    borderColor: AUTH_COLORS.border,
    gap: 12,
    shadowColor: "#000000",
    shadowOpacity: 0.18,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
  },
  cardHeader: {
    gap: 4,
  },
  cardTitle: {
    fontSize: 17,
    fontWeight: "800",
    color: AUTH_COLORS.text,
  },
  cardSubtitle: {
    fontSize: 13,
    lineHeight: 18,
    color: AUTH_COLORS.textMuted,
  },
  label: {
    fontSize: 12,
    fontWeight: "700",
    color: AUTH_COLORS.textSoft,
    textTransform: "uppercase",
    letterSpacing: 0.4,
  },
  inputGroup: {
    gap: 6,
  },
  input: {
    minHeight: 48,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: AUTH_COLORS.fieldBorder,
    backgroundColor: AUTH_COLORS.fieldBackground,
    paddingHorizontal: 14,
    fontSize: 15,
    color: AUTH_COLORS.text,
  },
  inputError: {
    borderColor: AUTH_COLORS.danger,
  },
  helperText: {
    fontSize: 12,
    lineHeight: 17,
    color: AUTH_COLORS.textMuted,
  },
  devHint: {
    fontSize: 12,
    lineHeight: 17,
    color: AUTH_COLORS.success,
    fontWeight: "700",
  },
  primaryBtn: {
    minHeight: 48,
    borderRadius: 14,
    backgroundColor: AUTH_COLORS.primary,
    borderWidth: 1,
    borderColor: "rgba(147,197,253,0.28)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  primaryBtnText: {
    color: "#ffffff",
    fontWeight: "800",
    fontSize: 14,
  },
  secondaryBtn: {
    minHeight: 46,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: AUTH_COLORS.border,
    backgroundColor: AUTH_COLORS.surfaceStrong,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  secondaryBtnText: {
    color: AUTH_COLORS.text,
    fontWeight: "700",
    fontSize: 13,
  },
  ghostRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
  },
  ghostBtn: {
    minHeight: 32,
    alignItems: "center",
    justifyContent: "center",
    paddingHorizontal: 4,
  },
  ghostBtnText: {
    color: "#93c5fd",
    fontSize: 13,
    fontWeight: "700",
  },
  doneIconWrap: {
    alignItems: "center",
    justifyContent: "center",
    marginTop: 4,
  },
  doneTitle: {
    textAlign: "center",
    color: AUTH_COLORS.text,
    fontWeight: "800",
    fontSize: 18,
  },
  sectionDivider: {
    height: 1,
    backgroundColor: AUTH_COLORS.border,
  },
  btnDisabled: {
    opacity: 0.55,
  },
});
